[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
cross_chain_token_bridge = "82ZuVtSrqVWfmuxH34R9ASdwLJ6TTNxGyBeBXbeZMycP"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[provider]
cluster = "localnet"
wallet = "../keys/signer.json"
